version: '3.8'

services:
  viewvault-server:
    image: lcmilstein/viewvault:auth0-fixed-redirect-20250921-132242
    container_name: viewvault-server
    pull_policy: always
    ports:
      - "8008:8000"
    volumes:
      - viewvault-server_db:/app/db
      - viewvault-server_posters:/app/static/posters
    environment:
      - DATABASE_URL=sqlite:///./db/viewvault.db
      - SECRET_KEY=${SECRET_KEY}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - JELLYFIN_USER_ID=${JELLYFIN_USER_ID}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - IMDB_API_KEY=${IMDB_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  viewvault-server_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/viewvault-server/db
  viewvault-server_posters:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/viewvault-server/posters
