version: '3.8'

services:
  viewvault-test:
    # Use image if specified, otherwise build locally
    image: ${WATCHLIST_IMAGE:-}
    build: .
    container_name: viewvault-test
    ports:
      - "3637:8000"
    volumes:
      - viewvault-test_watchlist-db:/app/db
      - viewvault-test_posters:/app/static/posters
    restart: unless-stopped

volumes:
  viewvault-test_watchlist-db:
  viewvault-test_posters:
